name: module3_task1
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  # single job
  build:
    runs-on: ubuntu-latest
    #two steps representing the task
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task1/setup.sh
      - run: cd module3_task1 && make help
      - run: cd module3_task1 && make build
      - run: cd module3_task1 && make clean
      - run: cd module3_task1 && make build
      - run: cd module3_task1 && make post POST_NAME="name" POST_TITLE="title"
